shop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [

    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')
    ]

shop/eApp/urls.py
from django.urls import path

from . import views

app_name = 'eApp'

urlpatterns = [

    path('',views.allProducts,name='allProducts'),
    path('<slug:c_slug>/',views.allProducts,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatDetail')

    ]

shop/search_app/urls.py
from django.urls import path

from . import views

app_name = 'search_app'

urlpatterns = [

    path('search/',views.searchResult,name='search_result')


    ]

shop/shop/urls.py
from shop import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eApp/',include("eApp.urls")),
    path('search/',include("search_app.urls")),
    path('cart/',include("cart.urls")),
]
if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/cart/models.py
from django.db import models
from eApp.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
        product = models.ForeignKey(Product,on_delete=models.CASCADE)
        cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
        quantity = models.IntegerField()
        active = models.BooleanField(default=True)

        class Meta:
            db_table='CartItem'

        def sub_total(self):
            return self.product.price * self.quantity

        def __str__(self):
            return '{}'.format(self.product)

shop/eApp/models.py
from django.db import models
from django.urls import reverse
# Create your models here:
class Category(models.Model):
    name=models.CharField(max_length=200,unique=True)
    slug=models.SlugField(max_length=200,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('eApp:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    desc = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='category', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('eApp:prodCatDetail', args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

shop/search_app/models.py
from django.db import models

# Create your models here.

shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from eApp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart=request.session.session_key

    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)

    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id= _cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

shop/eApp/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator  import Paginator,EmptyPage,InvalidPage
from . models import Category,Product

# Create your views here.
def allProducts(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug != None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)


    return render(request,'category.html',{'category':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

shop/search_app/views.py
from django.shortcuts import render
from eApp.models  import Product,Category
from django.db.models import Q

# Create your views here.
def searchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))

    return render(request,'search.html',{'query':query,'products':products})

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="'description" content="{% block metadescription %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>{% block title %}{% endblock %}</title>


</head>
<body>
<div>
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src=" {% static 'js/popper.min.js' %}" ></script>
<script src=" {% static 'js/bootstrap.min.js' %}" ></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        This is the cart page.Proceed to review items and place the order
{% endblock %}

{% block title %}
 CArt - FAH Company PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'eApp:allProducts' %}">Here</a>to continue shopping.
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="'col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your Items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" style="height:100;width:100px" alt="" class="float-left rounded custom_image"></a>
                </td>
                <td class="text=lef">
                    {{cart_item.product.name}}
                    <br>
                    sku: {{cart_item.product.id}}
                    <br>
                    Price: ${{cart_item.product.price}}
                    <br>
                    Qty : {{cart_item.quantity}} * $ {{cart_item}}
                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa fa-plus custom_icon"></i></a><br>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a><br>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                </td>
               {% else %}
                <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a><br>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                   {% endif %}
            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="table my_custom_thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Please review your shopping cart items before proceeding with the order payment
                    </td>
                </tr>
            <tr>
                <td class=text-left">
                    Your Total is:<strong>{{total}}</strong>
                </td>

            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'eApp:allProducts' %}" class="btn btn-secondary my_custom_button">Continue shopping</a>
        </div>
    </div>

</div>
{% endif %}
{% endblock %}

shop/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.desc|truncatewords:155}}
    {% else %}
        welcome to fah shop where you can buy anything...
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }}-FAH Shop
    {% else %}
        See our New Collections-FAH Shop
    {% endif %}
{% endblock %}
{% block content %}
{% if category %}
<div class="container-fluid">
    <div>
        <div class="row my_row">
            <div class="mx-auto">
                <p><a href="{% url 'eApp:allProducts' %}" >All Product Collections</a> </p>
            </div>
        </div>
    </div>
</div>
{% endif %}
<div class="mx-auto">
    {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
    </div>
    <br>
    <div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>
    </div>
    {% else %}
    <div>
        <img class="my_image my_image_padding" src="{% static 'img/banner5.jpg' %}" alt="our products" width="1500px" height="350px"/>
    </div>
    <br>

    <div class="content">
        <h1 class="text-center my_title" style="color: #A74AC7;">Our Product Collections</h1>
        <p class="text-justify my_text" style="font-size:18px;font-family;cursive;color:#D291BC;">"Sed ut perspicacity unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. , </p>
    </div>
    {% endif %}
<div class="container">
    <div class="row mx_auto">
            {% for product in products.object_list %}
            <div class="my-bottom-margin col-sm-12 col-md-4 col-lg-4 col-md-12 ">
                <div class="card"  style="font-size:18px;">
                    <a href="{{product.get_url}}"><img class="card-img-top " src="{{product.image.url}}" alt="{{product.name}}" height="250px" width="250px"> </a>
                    <div class="card-body">
                        <h4 class="card-title"style="text-transform:uppercase;color:#583759;">{{product.name}}</h4>
                        <p class="card-text"style="font-size:20px;color:#15317E;">${{product.price}}</p>
                        <p class="card-text" style="color:#583759;">{{product.desc}}</p>
                        <a class="btn" style="background-color:#B048B5;height:30px;width:100px;color:#583759;font-size:16px" href="{{product.get_url}}">View</a>
                    </div>
                </div>
            </div>
              {% endfor %}
    </div>
    <br>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>

</div>

{% endblock %}
</div>

shop/templates/footer.html
{% load static %}
<div class="footer navbar-fixed-bottom my_footer" style="background-color:#D462FF">
    <p class="text-center ">&copy: Fah shop pvt lmtd</p>
</div>

shop/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'eApp:allProducts' %}" ><img src="{% static 'img/logo.png' %}" alt="logoimage" width="200px" height="200px"/></a>
    </center>
</header>

shop/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Welcome
</body>
</html>

shop/templates/navbar.html
{% load static  %}
<nav class="navbar navbar-expand-lg navbar-light bg-light my_nav">
  <div class="collapse navbar-collapse" style="background-color:#D462FF" >
    <ul class="navbar-nav mr-auto"  style="font-size:15px">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown {% if 'eApp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          shop
          </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'eApp:allProducts' %}">All Products</a>
            {% for cat in links %}
            <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
            {% endfor %}
          </div>
        </li>
        {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link disabled" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
      </li>
        {% endif %}
    </ul>
       <form class="d-flex" action="{% url 'search_app:search_result' %}" method="get">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search" style="width:380px;"><span><button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search" ></i></button></span>
          </form>
  </div>
</nav>

shop/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{product.desc|truncatewords:155}}
{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name }}-FAH Shop
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto" style="font-size:17px;color:#84D39A;">
        <p style="color:#808080;"><a href="{% url 'eApp:allProducts' %}" style="font-size:17px;color:#808080;">Home   </a> >> <a href="{{product.category.get_url}}"style="font-size:17px;color:#808080;" >{{product.category}}</a>>>{{product.name}}</p>
    </div>
</div>
<br>
<div class="container-fluid">
    <div class="row" style="height:400px;width:100%;background-color:#D462FF">
        <div class="col-lg-6" style="margin-top:20px;">
            <img src="{{product.image.url}}" alt="{{product.name}}" style="height:450px;width:300px;">
        </div>
       <div class="col-lg-6">
           <div class="product_content">
                 <h1 class="my_product_title" style="font-size:20px;color:#667C26;">{{product.name}}</h1>
                <p class="price" style="font-size:20px;color:#15317E;">${{product.price}}</p>
                <p class="my-title" style="font-size:20px;color:#437C17;">Product Description</p>
                <p class="text-justify my_prod_text" style="font-size:20px;color:#437C17;"> {{product.desc}}</p>
                {% if product.stock <= 0 %}
                <p class="text-justify my_prod_text"><b>Out of stock</b></p>
                {% else %}
                <a class="btn" style="background-color:#B048B5;height:30px;width:100px;color:#583759;font-size:16px" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                {% endif %}
            </div>
       </div>
    </div>

</div>
    {% endblock %}

shop/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        we have vriety of products
{% endblock %}

{% block title %}
search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for :<b>{{query}}</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
            {% for product in products %}
            <div class="my-bottom-margin col-sm-12 col-md-4 col-lg-4 col-md-12 ">
                <div class="card">
                    <a href="{{product.get_url}}"><img class="card-img-top " src="{{product.image.url}}" alt="{{product.name}}" height="250px" width="250px"> </a>
                    <div class="card-body">
                        <h4 class="card-title">{{product.name}}</h4>
                        <p class="card-text">${{product.price}}</p>
                        <p class="card-text">{{product.desc}}</p>
                         <a href="">Add to Cart</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">0 results found </p>
            </div>
              {% endfor %}
    </div>
</div>
{% endblock %}